// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetClinicApi.Data;

#nullable disable

namespace PetClinicApi.Migrations
{
    [DbContext(typeof(PetClinicContext))]
    [Migration("20260509130422_AdatokFeltoltve")]
    partial class AdatokFeltoltve
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PetClinicApi.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "annakovacs@gmail.com",
                            FirstName = "Kovacs",
                            LastName = "Anna",
                            Phone = "+36 20 123 4567"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Nagy",
                            LastName = "Béla",
                            Phone = "+36 30 987 6543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "csilla.h@freemail.hu",
                            FirstName = "Horváth",
                            LastName = "Csilla"
                        });
                });

            modelBuilder.Entity("PetClinicApi.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 2019,
                            Breed = "Labrador",
                            Name = "Bodri",
                            OwnerId = 1,
                            Species = "Kutya"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 2021,
                            Breed = "Európai rövidszőrű",
                            Name = "Cirmos",
                            OwnerId = 1,
                            Species = "Macska"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 2020,
                            Breed = "Németjuhász",
                            Name = "Rex",
                            OwnerId = 2,
                            Species = "Kutya"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 2022,
                            Name = "Hópihe",
                            OwnerId = 3,
                            Species = "Nyúl"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 2018,
                            Breed = "Perzsa",
                            Name = "Mici",
                            OwnerId = 3,
                            Species = "Macska"
                        });
                });

            modelBuilder.Entity("PetClinicApi.Entities.Pet", b =>
                {
                    b.HasOne("PetClinicApi.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetClinicApi.Entities.Owner", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
